# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:latest

        working_directory: ~/repo

        steps:
            - checkout

            - restore_cache:
                keys:
                    - dependencies-{{ checksum "yarn.lock" }}
                    # Fallback to using the latest cache if no exact match is found
                    - dependencies-

            - run:
                name: Preparing greenkeeper-lockfile
                command: |
                    echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
                    source $BASH_ENV
                    yarn global add greenkeeper-lockfile@1

            - run:
                name: Installing Dependencies
                command: yarn install

            - run:
                name: Updating greenkeeper lockfile
                command: greenkeeper-lockfile-update

            - save_cache:
                paths:
                    - node_modules
                key: dependencies-{{ checksum "yarn.lock" }}
        
            - run:
                name: Running Unit Tests
                command: yarn test:ci
                environment:
                    JEST_JUNIT_OUTPUT: "reports/jest/test-results.xml"
      
            - store_test_results:
                path: reports

            - run:
                name: Running Metrics
                command: yarn metrics:ci

            - run:
                name: Uploading greenkeeper lockfile
                command: greenkeeper-lockfile-upload
